[package]
name = "protonup-cachyos"
version = "0.1.0"
edition = "2021"

[dependencies]
curl = "0.4"
xz2 = "0.1"
tar = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
libc = "0.2"
